name: Get Commit ID from Tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name'
        required: true

jobs:
  get-commit-id:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # Use the standard action to checkout code

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt # If you have any Python dependencies

      - name: Get Commit ID
        run: python main.py ${{ github.event.inputs.tag }}
