name: Print Commit ID

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name'
        required: true

jobs:
  print-commit-id:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Commit ID
        run: |
          tag_name=ytg1.0  # Specify your tag name here
          commit_id=$(git rev-list -n 1 $tag_name)
          echo "Commit ID for $tag_name: $commit_id"
